---
title: "Run SPLS For ADNI Data"
author: "Melissa Nunez"
date: "10/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r load RANN Data, echo=FALSE, include = FALSE}
# RQ: Is there an association between Cortical Thickness and Subcortical Volume? i.e can Cortical thickness predict cortical volume ?

library(caret)
#install.packages("spls")
library(spls)
library(ggplot2)
library(readxl)
library(knitr)
library(kableExtra)
library(gplots)

ADNI_Set1 <- read_excel("/Users/user/Dropbox/Melissa/imputation/ADNI/dataset/ADNI\ 6\ datasets\ creation\ 2018_06_04.xlsx", sheet = 2)

ADNI_Set1 <- ADNI_Set1[which(ADNI_Set1$dataset1 == 1 & ADNI_Set1$month_dataset1 == 0),]
head(ADNI_Set1,10)

CT <- grep("CT_",names(ADNI_Set1))
SV <- grep("SV_",names(ADNI_Set1))
SV <- SV[17:66]
CT_Set <- as.matrix(ADNI_Set1[,CT])
SV_Set <- as.matrix(ADNI_Set1[,SV])
CorticalGM <- grep("CorticalGM", colnames(SV_Set))
CorticalWM <- grep("CorticalWM", colnames(SV_Set))
SuborticalWM <- grep("SubcorticalGM", colnames(SV_Set))
Supratentorial <- grep("SupraTentorial", colnames(SV_Set))
TotalGM <- grep("TotalGM", colnames(SV_Set))
Vessel <- grep("Vessel", colnames(SV_Set))
HypoIntensities <- grep("WMHypoIntensities", colnames(SV_Set))
OpticChiasm <- grep("OpticChiasm", colnames(SV_Set))
FifthVentricle <- grep("FifthVentricle", colnames(SV_Set))
SV <- SV[-c(CorticalGM,CorticalWM,SuborticalWM,Supratentorial,TotalGM,Vessel,HypoIntensities,OpticChiasm,FifthVentricle)]
SV_Set <- as.matrix(ADNI_Set1[,SV])

#apply(SV_Set,2,function(x)sum(is.na(x)==TRUE))

```



```{r Explore spls, echo=FALSE, include = FALSE}
cv <- cv.spls(CT_Set, SV_Set, eta = seq(0.1,0.9,0.1), K = c(1:10) )

mod <- spls(CT_Set, SV_Set_complete, eta = cv$eta.opt, K = cv$K.opt )
print(mod)
names(mod)
typeof(mod$betahat)
```


```{r Run spls, echo=FALSE, include = FALSE}

# Bootstrap sample data 100 times
resamples <- lapply(1:100, function(i) sample(nrow(ADNI_Set1), replace = T))


splsr_opt_coef <- function(x,y,nums)
  {

j=1
l <- list()

for (i in 1:100) {

x_boot <- x[nums[[i]],] 
y_boot <- y[nums[[i]],]
  
cv <- cv.spls(x_boot, y_boot, eta = seq(0.1,0.9,0.1), K = c(1:10) )

mod <- spls(x_boot, y_boot, eta = cv$eta.opt, K = cv$K.opt )

coefs <- mod$betahat

l[[i]] <- coefs
    j <- j + 1
    
}

list_opt_coefs <- l
assign("list_opt_coefs",list_opt_coefs,.GlobalEnv)

}

splsr_opt_coef(CT_Set, SV_Set, resamples)

# Calculate mean and standard deviation of each coefficient
vec <- unlist(list_opt_coefs, use.names = FALSE)
DIM <- dim(list_opt_coefs[[1]])
n <- length(list_opt_coefs)

list.mean <- tapply(vec, rep(1:prod(DIM),times = n), mean)
attr(list.mean, "dim") <- DIM
list.mean <- as.data.frame(list.mean)

list.sd <- tapply(vec, rep(1:prod(DIM),times = n), sd)
attr(list.sd, "dim") <- DIM
list.sd <- as.data.frame(list.sd)

# Calculate z-score for each coeefficient
z.score_mat <- list.mean/list.sd

colnames(z.score_mat) <- colnames(SV_Set)
rownames(z.score_mat) <- colnames(CT_Set)

thresh=as.matrix(z.score_mat)
thresh[abs(thresh)<1.96]<-0
thresh <- thresh[as.logical(rowSums(thresh != 0)), as.logical(colSums(thresh != 0))]


save.image("/Users/user/Dropbox/Melissa/PLSR/SPLS_ADNI.Rdata")
```
